name: 'Hellow World Docker Action'
description: 'Say hello to a user or the world.'

inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    defaut: 'world'
outputs:
  time:
    description: 'The time we said hello.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
